name: Replace data in package.json
on: push

permissions:
  contents: write

jobs:
  run-script:
    name: replace data

    # We will only run this action when this repository isn't the template repository
    if: >-
      ${{ !github.event.repository.is_template && github.run_number == 1 }}

    runs-on: ubuntu-latest
    steps:
      - name: Configure Git
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR_EMAIL}"
        shell: bash

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Replace version
        run: |
          sed -i "s/\"version\": \".*\"/\"version\": \"1.0.0\"/" package.json
      - name: Replace name and email
        run: |
          sed -i "s/\"author\": \".*\"/\"author\": \"${{ github.actor }}\"/" package.json
      - name: Replace repository
        run: |
          sed -i "s/\"repository\": \".*\"/\"repository\": \"${{ github.repositoryUrl }}\"/" package.json

      - name: Commit changes
        run: |
          git add package.json
          git commit -m "Replace data in package.json"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
